name: revisei
description: "App Revisei - Sincronização Web/Mobile para estudos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_quill: ^11.4.2
  fl_chart: ^0.66.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
